### ISSUE TITLE
Can`t open in code editor

### ISSUE THREAD

**Issue by chenpaner** [Pullusb/devTools#12]
dev tools 2, 7, 3    blender 4.2.3

![111111111111111111](https://github.com/user-attachments/assets/70880adb-cc63-4eab-b49c-7759b43bbc42)

![22222222222222222](https://github.com/user-attachments/assets/322350a2-957d-4c08-ba5c-e33938aca57b)

![333333333333](https://github.com/user-attachments/assets/6b652d59-3a36-4758-8cb1-2f8c31b40205)

![44444444444444](https://github.com/user-attachments/assets/066f8db8-e0b2-42a5-92b0-a87cd94f8907)

![5555555555](https://github.com/user-attachments/assets/69f5e343-e3ba-4cf4-bbe5-9c04889e82d3)

**Comment by Pullusb** [comment]
Hi,
Should be fixed now.
Reopen the issue if there is still a problem

Note that editor arguments are ignored at the moment (only automated for VScode or Codium).
I need to add the support for argument, but lot's of thing on my plate at the moment... could take a while.
Cheers
