### ISSUE TITLE
Error after clicking on "Time selected code" button

### ISSUE THREAD

**Issue by xan2622** [Pullusb/devTools#2]
Hi.

I am using DevTools 1.1.2 with Blender 2.82 (official) and I have noticed an error after clicking on the 
**Time selected code** button.

> Traceback (most recent call last):
>   File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SB_devTools.py", line 388, in execute
>     end_line = text.lines[select_range[-1]+1]#get line after to insert #OUT OF RANGE IF LAST LINE !
> IndexError: bpy_prop_collection[index]: index 1 out of range, size 1
> 
> location: <unknown location>:-1

**Comment by Pullusb** [comment]
Ok. thank you for the feedback. That functionality was kind of a WIP 😅.
Will check this when I'll get some free time. (Certainly in the middle of next week).

**Comment by Pullusb** [comment]
Yo @xan2622 ! I completely forgot about this !
Fixed it while adding a new function.

Better late than never I guess ^^'
